version: 0.2

phases:
  build:
    commands:
    - chmod +x scripts/*.sh

artifacts:
  base-directory: 10-Monitoring-and-Rollback-with-CloudWatch-and-CodeDeploy
  files:
  - app.py
  - requirements.txt
  - appspec.yml
  - scripts/**/*
